name: Preview

on:
  pull_request:

concurrency:
  group: seaql.github.io
  cancel-in-progress: false

env:
  YARN_IGNORE_NODE: 1
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  deploy:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.0

      - uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: 3.6.1
          cache: false

      - uses: actions/cache@v4
        with:
          key: ${{ github.repository }}-${{ github.ref_name }}
          path: |
            ~/.yarn
            SeaORM/node_modules
            SeaORM/.docusaurus
            SeaORM/build
            SeaORM-X/node_modules
            SeaORM-X/.docusaurus
            SeaORM-X/build
            sea-orm-pro/node_modules
            sea-orm-pro/.docusaurus
            sea-orm-pro/build
            Blog/node_modules
            Blog/.docusaurus
            Blog/build
            Seaography/node_modules
            Seaography/.docusaurus
            Seaography/build
            SeaStreamer/node_modules
            SeaStreamer/.docusaurus
            SeaStreamer/build

      - run: sh preview.sh ${{ github.event.number }}

      - run: sh build.sh

      - uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          source-dir: docs
          umbrella-dir: preview
          custom-url: www.sea-ql.org
          action: auto
